name: Run Python filter news Every 1 hour

on:
  schedule:
    - cron: '0 * * * *'   # 每1小時執行一次 (注意：此時間為 UTC 時間)
  workflow_dispatch:        # 允許手動觸發
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 指定你使用的 Python 版本，例如 '3.11'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            sent_big_news.json
            visited_links.json
            last_checked_date.txt
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule beautifulsoup4 lxml

      - name: Run the script
        run: |
          python finter_news.py   # 將 'run.py' 換成你要執行的程式檔案名稱

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: |
            sent_big_news.json
            visited_links.json
            last_checked_date.txt
          key: ${{ runner.os }}-cache

      # - name: Ignore pycache
      #   run: |
      #     git config --global user.name 'rrvfqo'
      #     git config --global user.email 'rrvfqo@gmail.com'
      #     if ! grep -qx "__pycache__/" .gitignore; then
      #       echo "__pycache__/" >> .gitignore
      #       git add .gitignore
      #       git commit -m 'Update .gitignore to ignore __pycache__'
      #     fi
      #     if [ -d "__pycache__/" ]; then
      #       git rm -r --cached __pycache__/
      #     fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'rrvfqo'
          git config --global user.email 'rrvfqo@gmail.com'
          git add sent_big_news.json visited_links.json last_checked_date.txt
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m 'Update news files'
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



