name: Run Python filter news Every 1 hour

on:
  schedule:
    - cron: '0 * * * *'   # 每1小時執行一次 (注意：此時間為 UTC 時間)
  workflow_dispatch:        # 允許手動觸發
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 指定你使用的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run the script
        run: |
          python filter_news.py

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            visited_links.txt
            last_checked_date.txt
          key: ${{ runner.os }}-cache

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: |
            visited_links.txt
            last_checked_date.txt
          key: ${{ runner.os }}-cache

      - name: Commit and push changes
        run: |
          git config --global user.name 'rrvfqo'
          git config --global user.email 'rrvfqo@gmail.com'
          git add visited_links.txt last_checked_date.txt
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m 'Update news files'
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



