name: Run Python filter news Every 1 hour

on:
  schedule:
    - cron: '0 * * * *'   # 每1小時執行一次 (注意：此時間為 UTC 時間)
  workflow_dispatch:        # 允許手動觸發
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 指定你使用的 Python 版本，例如 '3.11'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            sent_big_news.json
            visited_links.json
            last_checked_date.txt
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule beautifulsoup4 lxml

      - name: Run the script
        run: |
          python run.py   # 將 'run.py' 換成你要執行的程式檔案名稱

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: |
            sent_big_news.json
            visited_links.json
            last_checked_date.txt
          key: ${{ runner.os }}-cache

  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run script
        run: |
          python filter_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sent_big_news.json visited_links.json
          git commit -m 'Update news files'
          git push
